    name: TestPlugin
    main: com.gmail.nerdx86.MiningToolKit.MiningToolKit
    version: 0.0.1
    commands:
      autominer:
        description: This is a demo command.
        usage: /<command> [radius]
        aliases: [am]
        permission: <plugin name>.autominer
        permission-message: You don't have <permission>
      autolighter:
        description: This is a demo command.
        usage: /<command> [intensity]
        aliases: [al]
        permission: <plugin name>.autolighter
        permission-message: You don't have <permission>
      nanodissolve:
        description: This is a demo command.
        usage: /<command> [radius]
        aliases: [nd]
        permission: <plugin name>.nanodissolve
        permission-message: You don't have <permission>        
      tothesky:
        description: This is a demo command.
        usage: /<command>
        aliases: [tts]
        permission: <plugin name>.tothesky
        permission-message: You don't have <permission>
      makealake:
        description: This is a demo command.
        usage: /<command>
        aliases: [mal]
        permission: <plugin name>.makealake
        permission-message: You don't have <permission>
      tothere:
        description: This is a demo command.
        usage: /<command>
        aliases: [tt]
        permission: <plugin name>.tothere
        permission-message: You don't have <permission>
      mininginventory:
        description: This is a demo command.
        usage: /<command> [options]
        aliases: [mi]
        permission: <plugin name>.mininginventory
        permission-message: You don't have <permission>
      mininglaser:
        description: This is a demo command.
        usage: /<command> [distance]
        aliases: [ml]
        permission: <plugin name>.mininglaser
        permission-message: You don't have <permission>

      